name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.12.0
homepage: https://github.com/tobrun/flutter-mapbox-gl
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    path: mapbox_gl_platform_interface
  mapbox_gl_web:
    path: mapbox_gl_web

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web:
        default_package: mapbox_gl_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  flutter: ">=2.0.0"
